/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    HeatMap: typeof import('./src/components/Charts/HeatMap.vue')['default']
    HeatMapChat: typeof import('./src/components/HeatMapChat.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
